# Generated by Django 4.1.2 on 2022-10-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_myuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="person_id",
        ),
        migrations.AddField(
            model_name="myuser",
            name="role_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.roles",
            ),
        ),
        migrations.AlterField(
            model_name="financial",
            name="person_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinic.myuser"
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="person_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinic.myuser"
            ),
        ),
        migrations.DeleteModel(
            name="Persons",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
