# Generated by Django 4.1.2 on 2022-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_remove_users_person_id_myuser_role_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="clinic_staff",
            field=models.BooleanField(default=False),
        ),
    ]
