# Generated by Django 4.1.2 on 2022-10-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_myuser_clinic_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="role_id",
        ),
        migrations.DeleteModel(
            name="Roles",
        ),
    ]
