# Generated by Django 4.1.2 on 2022-10-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_remove_myuser_role_id_delete_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
