# Generated by Django 4.1.2 on 2022-10-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_alter_financial_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
