# Generated by Django 4.1.2 on 2022-10-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_alter_patients_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnoses",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
