# Generated by Django 4.1.2 on 2022-10-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0008_alter_diagnoses_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patients",
            name="diagnose_id",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="person_id",
        ),
        migrations.AddField(
            model_name="patients",
            name="firstname",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patients",
            name="lastname",
            field=models.CharField(default="smith", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="financial",
            name="person_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinic.patients"
            ),
        ),
        migrations.CreateModel(
            name="Medicaldata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnose_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.diagnoses",
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.patients",
                    ),
                ),
            ],
        ),
    ]
