# Generated by Django 4.1.2 on 2022-10-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0009_remove_patients_diagnose_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financial",
            old_name="creditcard_no",
            new_name="creditcardno",
        ),
        migrations.RenameField(
            model_name="financial",
            old_name="person_id",
            new_name="personid",
        ),
        migrations.RenameField(
            model_name="medicaldata",
            old_name="diagnose_id",
            new_name="diagnoseid",
        ),
        migrations.RenameField(
            model_name="medicaldata",
            old_name="person_id",
            new_name="personid",
        ),
    ]
