# Generated by Django 4.1.2 on 2022-10-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0010_rename_creditcard_no_financial_creditcardno_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financial",
            old_name="creditcardno",
            new_name="creditcard",
        ),
    ]
