# Generated by Django 4.1.2 on 2022-10-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0012_alter_financial_personid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="personid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinic.patients"
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="diagnoseid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinic.diagnoses"
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="personid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinic.patients"
            ),
        ),
    ]
