# Generated by Django 4.1.2 on 2022-10-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0013_alter_financial_personid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financial",
            old_name="personid",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="medicaldata",
            old_name="diagnoseid",
            new_name="diagnose",
        ),
        migrations.RenameField(
            model_name="medicaldata",
            old_name="personid",
            new_name="person",
        ),
    ]
