# Generated by Django 4.1.2 on 2022-10-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0015_auto_20221028_1202"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.CharField(max_length=300)),
            ],
        ),
    ]
