# Generated by Django 4.1.2 on 2022-10-30 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0016_intra"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicaldata",
            name="diagnose_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 30, 14, 7, 32, 718940)
            ),
        ),
    ]
