# Generated by Django 4.1.2 on 2022-10-30 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0017_medicaldata_diagnose_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicaldata",
            name="diagnose_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 30, 14, 10, 39, 208655)
            ),
        ),
    ]
